# Generated by Django 3.1 on 2020-08-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conaferapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by_user',
            field=models.ForeignKey(default=int, on_delete=django.db.models.deletion.CASCADE, to='conaferapi.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
