# Generated by Django 3.1 on 2020-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('valor_nominal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=4)),
                ('endereco_ip', models.CharField(max_length=20)),
                ('data_solicitacao', models.CharField(max_length=10)),
                ('banco', models.CharField(max_length=60)),
                ('nome_cliente', models.CharField(max_length=120)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_by_user', models.IntegerField()),
            ],
            options={
                'db_table': 'emprestimo',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('identificador_emprestimo', models.IntegerField()),
                ('data_pagamento', models.CharField(max_length=10)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_by_user', models.IntegerField()),
            ],
            options={
                'db_table': 'pagamento',
            },
        ),
    ]
