# Generated by Django 3.1 on 2020-08-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
