# Generated by Django 3.1 on 2020-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_api', '0002_auto_20200831_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
