# Generated by Django 3.1 on 2020-09-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_api', '0004_auto_20200907_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='saldo_devedor',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_nominal',
            field=models.TextField(max_length=20),
        ),
    ]
