# Generated by Django 3.1 on 2020-09-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_api', '0006_auto_20200908_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='saldo_devedor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='valor_nominal',
            field=models.TextField(),
        ),
    ]
