# Generated by Django 3.1 on 2020-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo_api', '0007_auto_20200908_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='identificador_emprestimo',
            field=models.IntegerField(),
        ),
    ]
