# Generated by Django 3.1 on 2020-08-31 13:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('birthdate', models.CharField(max_length=10)),
                ('admission_date', models.CharField(max_length=10)),
                ('job_role', models.CharField(max_length=120)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('created_by_user', models.IntegerField()),
            ],
            options={
                'db_table': 'naver',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('navers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('created_by_user', models.IntegerField()),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
