# Generated by Django 3.1 on 2020-08-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navedexapi', '0002_auto_20200819_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by_user',
        ),
    ]
